required = [
  "github.com/alecthomas/gometalinter",
  "github.com/vektra/mockery/cmd",
  "github.com/cweill/gotests/gotests",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gorm.io/gorm"
  version = "1.21.4"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.9.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.8.0"

[[constraint]]
  name = "github.com/go-log/log"
  version = "0.2.0"

[[constraint]]
  name = "gorm.io/driver/postgres"
  version = "0.2.4"

[[constraint]]
  name = "github.com/caarlos0/env"
  version = "6.5.0"
