required = [
  "github.com/alecthomas/gometalinter",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gorm.io/gorm"
  version = "1.21.4"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.9.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.8.0"

[[constraint]]
  name = "github.com/go-log/log"
  version = "0.2.0"

[[constraint]]
  name = "gorm.io/driver/postgres"
  version = "0.2.4"

[[constraint]]
  name = "github.com/caarlos0/env"
  version = "6.5.0"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.5.1"

[[constraint]]
  name = "github.com/thewizardplusplus/go-http-utils"
  version = "1.1.1"

[[constraint]]
  name = "github.com/streadway/amqp"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-gorm/datatypes"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/alecthomas/kong"
  version = "0.2.16"

[[constraint]]
  name = "github.com/sethvargo/go-password"
  version = "0.2.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/gorilla/schema"
  version = "1.2.0"
