required = [
  "github.com/alecthomas/gometalinter",
  "github.com/vektra/mockery/cmd",
  "github.com/cweill/gotests/gotests",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gorm.io/gorm"
  version = "1.21.4"
